version: '3'

services:
  postgresql:
    container_name: postgresql
    build:
      context: docker/services/postgresql
      dockerfile: Dockerfile
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

  mailcatcher:
    container_name: mailcatcher
    build:
      context: docker/services/mailcatcher
      dockerfile: Dockerfile
    ports:
      - 1080:1080
      - 1025:1025
